# Generated by Django 4.1.6 on 2023-08-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_bloodbank_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
