# Generated by Django 4.2.4 on 2023-08-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230821_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('event_time', models.CharField(blank=True, max_length=50, null=True)),
                ('beneficiary', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
