# Generated by Django 4.2.4 on 2023-08-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_person_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
