# Generated by Django 4.2.4 on 2023-08-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_events_bloodbank_website_alter_person_phone_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='event',
        ),
    ]
